### ISSUE TITLE
Failed to alter package manager state

### ISSUE THREAD

**Issue by Tooniis** [chenxiaolong/AlterInstaller#8]
I'm getting this:
```
02-01 00:36:07.551   540   540 E AlterInstaller: Failed to alter package manager state
02-01 00:36:07.551   540   540 E AlterInstaller: java.lang.NoSuchMethodException: android.util.Xml.resolvePullParser [class java.io.InputStream]
02-01 00:36:07.551   540   540 E AlterInstaller: 	at java.lang.Class.getMethod(Class.java:2072)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.chiller3.alterinstaller.Main.resolvePullParser(Unknown Source:10)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.chiller3.alterinstaller.Main.alterXml(SourceFile:1)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.chiller3.alterinstaller.Main.alterXml(SourceFile:13)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.chiller3.alterinstaller.Main.apply(Unknown Source:23)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.chiller3.alterinstaller.Main.main(Unknown Source:74)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-01 00:36:07.551   540   540 E AlterInstaller: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
```
Running Android 11 (LineageOS 18.1)

**Comment by chenxiaolong** [comment]
Sorry, Android 11 isn't supported by AlterInstaller. Android versions older than 12 do not have the necessary code for reading and writing Android's binary XML files (`/data/system/packages.xml` in this case).
